language: python
python:
  - "2.7"
  - "3.3"

# command to install dependencies
install:
  - pip install six --use-mirrors
  - pip install setuptools==1.4
  - pip install suds-jurko
  - pip install coverage coveralls --use-mirrors # test coverage
# command to run tests
script:
  - nosetests --with-coverage --cover-package=fortepy

after_success:
  - coveralls
