language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"

# command to install dependencies
install:
  - pip install six --use-mirrors
  - pip install suds-jurko --use-mirrors

# command to run tests
script:
  - nosetests --with-coverage --cover-package=fortepy

after_success:
  - coveralls
